<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>
<body>
<div class="container">
    <?php echo $this->getContent(); ?>
</div>

<div class="col-md-6">
    <h2>Login</h2>
    <?php echo $this->tag->form("login/start"); ?>
    <div class="col-md-6">
    <div class="form-group">
        <label for="email">E-Mail</label>
        <?php echo $this->tag->textField(["email", "class" => "form-control", "placeholder" => "Enter Email Address"]); ?>
    </div>

    <div class="form-group">
        <label for="password">Password</label>
        <?php echo $this->tag->passwordField(["password", "class" => "form-control", "placeholder" => "Enter Password"]); ?>
    </div>

    <div class="form-group">
        <?php echo $this->tag->submitButton(["Login", "class" => "btn btn-primary"]); ?>
    </div>

</form>
<p>Don't have one? <?php echo $this->tag->linkTo([
        "signup", 
        "Sign Up Here!",
        'style' => 'color:grey' 
    ]);?>
</p>
</div>
</body>
</html>
